version: "3.8"

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: ${PROJECT_NAME}_wp
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    restart: always

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
